# Generated by Django 4.2.5 on 2023-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
