# Generated by Django 4.2.5 on 2023-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitems_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
